## tools/stage-render.R
##
## Reproducible render-and-stage hook for the manuscript pool.
## Invoked automatically by each paper's report.Rmd via the
## `knit:` YAML field, which RStudio's Knit button, the
## `rmarkdown::render()` function, and a Makefile target all
## respect.
##
## Behaviour:
##
##   1. Calls `rmarkdown::render(input)` to produce the PDF in
##      the manuscript directory (canonical workflow unchanged;
##      `report.pdf` continues to land alongside `report.Rmd`).
##   2. Computes a staging filename:
##        <NN-slug>[-short]-<YYYY-MM-DD>-dN.pdf
##      where <NN-slug> is the manuscript directory name, the
##      `-short` suffix appears for `report_short.Rmd` only, and
##      `dN` is the per-day draft counter starting at d1 and
##      incrementing for each render on the same calendar day.
##   3. Copies the produced PDF to
##      `analysis/report/share/<staging-filename>`.
##   4. Appends an entry to `analysis/report/share/MANIFEST.md`
##      recording the staged filename, the source path, and the
##      render timestamp.
##
## YAML usage in each report.Rmd:
##
##   knit: (function(input, ...)
##           rmarkdown::render(input, ...,
##             output_format = NULL,
##             knit_root_dir = dirname(input)) |>
##           (function(out) source(file.path(rprojroot::find_root(
##             rprojroot::has_file('DESCRIPTION')), 'tools',
##             'stage-render.R'))$value$stage_render(input, out))())
##
## ...but in practice the YAML hook is the single line:
##
##   knit: (function(input, encoding)
##           source(here::here('tools/stage-render.R'))$value(input))
##
## See `set_knit_hook_in_yaml()` below for the canonical
## one-liner that we paste into each Rmd's YAML.

stage_render <- function(input, encoding = 'UTF-8', ...) {
  ## Resolve the project root via rprojroot or via a known
  ## ancestor directory. Both `here::here()` and rprojroot
  ## return the project root regardless of the working
  ## directory at the time of knit.
  if (requireNamespace('rprojroot', quietly = TRUE)) {
    proj_root <- rprojroot::find_root(
      rprojroot::has_file('DESCRIPTION'))
  } else {
    proj_root <- here::here()
  }

  share_dir <- file.path(proj_root, 'analysis', 'report', 'share')
  dir.create(share_dir, showWarnings = FALSE, recursive = TRUE)

  ## Render the document via the standard rmarkdown::render()
  ## pathway; this preserves all other YAML options. The
  ## resulting PDF lands in the manuscript directory as usual.
  out_path <- rmarkdown::render(input, encoding = encoding, ...,
                                envir = new.env())

  ## Compute the staging filename.
  manuscript_dir <- basename(dirname(normalizePath(input)))
  rmd_base <- tools::file_path_sans_ext(basename(input))
  short_suffix <- if (grepl('_short$', rmd_base)) '-short' else ''
  date_stamp <- format(Sys.Date(), '%Y-%m-%d')

  ## Per-day draft counter: scan share_dir for existing files
  ## matching the same prefix and date, take max(N) + 1.
  prefix <- paste0(manuscript_dir, short_suffix, '-', date_stamp,
                   '-d')
  existing <- list.files(share_dir,
                         pattern = paste0('^', prefix, '\\d+\\.pdf$'))
  next_draft <- if (length(existing) == 0) {
    1L
  } else {
    nums <- as.integer(sub(
      paste0('^', prefix, '(\\d+)\\.pdf$'), '\\1', existing))
    max(nums, na.rm = TRUE) + 1L
  }

  staged_name <- paste0(prefix, next_draft, '.pdf')
  staged_path <- file.path(share_dir, staged_name)
  file.copy(out_path, staged_path, overwrite = FALSE)

  ## Update MANIFEST.md with one row per staged PDF.
  manifest_path <- file.path(share_dir, 'MANIFEST.md')
  if (!file.exists(manifest_path)) {
    cat('# Staged manuscript drafts\n\n',
        '*Auto-generated by `tools/stage-render.R`.',
        ' Each row records one render-and-stage event.*\n\n',
        '| Staged PDF | Source | Render timestamp |\n',
        '|---|---|---|\n',
        sep = '', file = manifest_path)
  }
  src_disp <- sub('^/Users/[^/]+/Dropbox', '~/Dropbox',
                  normalizePath(input))
  src_disp <- sub('^/Users/[^/]+', '~', src_disp)
  ts <- format(Sys.time(), '%Y-%m-%d %H:%M:%S %Z')
  cat(sprintf('| `%s` | `%s` | %s |\n',
              staged_name, src_disp, ts),
      file = manifest_path, append = TRUE)

  message(sprintf('Staged: %s', staged_path))
  invisible(out_path)
}

## When sourced for use in a YAML knit: hook, calling the
## sourced expression returns the function. The pattern
##
##   source('.../stage-render.R')$value(input)
##
## works because R's `source()` returns a list with `value`
## bound to the result of the last top-level expression. We
## therefore end with a bare reference to the function.
stage_render
